language: java
jdk:
  - openjdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  yarn: true
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
install: mvn dependency:resolve --batch-mode
script:
  - mvn clean --batch-mode
  - mvn package --batch-mode
deploy:
  - provider: script
    script: .ci/deploy.sh
    skip_cleanup: true
    on:
      # branch: master
      branch: ST6RI-323
      tags: false
  - provider: script
    script: .ci/release.sh
    skip_cleanup: true
    on:
      tags: true