language: java
jdk:
  - openjdk17
env:
  global:
    - MAVEN_OPTS=-Dhttps.protocols=TLSv1.2
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  yarn: true
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
install: skip
script:
  - ./mvnw clean --batch-mode
  - ./mvnw install --batch-mode
deploy:
  - provider: script
    script: .ci/deploy.sh
    skip_cleanup: true
    on:
      branch: master
      tags: false
  - provider: script
    script: .ci/release.sh
    skip_cleanup: true
    on:
      tags: true